behaviors:
  Crawler:
    trainer_type: ppo
    init_path: results/soloCrawler/Crawler/Crawler-933160.pt
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    time_horizon: 64
    summary_freq: 1000
    max_steps: 10000000
    self_play:
      save_steps: 5000
      swap_steps: 10000
      max_policies: 5

  Worm:
    trainer_type: ppo
    init_path: results/soloWorm/Worm/Worm-6957276.pt
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    time_horizon: 64
    summary_freq: 1000
    max_steps: 10000000
